### ISSUE TITLE
Try WR with Servo

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#101]
I managed to rebase our current state to the latest version. (I had to squash it because 84 patch were just to much...)  https://github.com/szeged/webrender/tree/rebase_upstream

There are some things that need to be resolved first (most probably i missed something), because it segfaults in some tests, and with the blob example we can only see black rectangles.

After its done, we can hook it up with Servo and try it. (@zakorgy already working on this part.)

**Comment by zakorgy** [comment]
I have managed to connect our WR with Servo. And it looks promising:
![servo_vulkan](https://user-images.githubusercontent.com/11725775/37393523-9b15cdd6-2771-11e8-8934-52549741aa75.png)
I will upload my code to szeged/servo and link the branch soon.

**Comment by zakorgy** [comment]
Link for the above mentioned branch: https://github.com/szeged/servo/tree/gfx_wr_57

**Comment by dati91** [comment]
About the crash: we wanted to reuse a texture, which is currently used in the frame and we didn't submitted the command yet. I added a check for that and now it works fine.

Another crash was that our `max_texture_size` is `2048` (from the physical_device's limit) and we didn't trimmed the size properly.

**Comment by dati91** [comment]
We managed to rebase everything and get the servo working with it, so I'm closing this.
