### ISSUE TITLE
Rework command buffer submitting

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#118]
```
ERROR:: [DS] Object: 0x7f2b421a6400 | You are adding vkQueueSubmit() to command buffer 0x7f2b421a6400 that is invalid because bound DescriptorSet 0x1602 was destroyed or updated.
```
This comes from `bind_locals` and `bind_textures`.
Currently we batching all the commands and submitting at the end, before calling present.
Instead of this, we should submit after a render pass (in renderer.rs' `draw_tile_frame`).

**Comment by dati91** [comment]
So I revisited this issue, and the main reason we are submitting after each draw call is that we may use the same program/pipeline multiple times. For binding a texture, we need to write the descriptor set, but it is not a command that we can queue, it changes the (global) state of the pipeline.
Submitting the current state to the gpu solve this, but maybe we can do better. 

A possible solution is that we allocate more descriptor sets. I'm not sure how efficient this solution would be, because we need to define at creation time the max number of descriptor sets in a pool, and in a (theoretical?) worst case we can run out of it. Maybe we can create another pool if this happens, but this may complicate things even more.

@kvark Any thoughts on this?

**Comment by kvark** [comment]
@dati91 
> For binding a texture, we need to write the descriptor set, but it is not a command that we can queue,

We don't need to queue the write itself, it's immediate. As long as the descriptor set is not used in any in-flight command buffers, we should be just fine writing to it and then immediately issuing commands using it. I suppose we just need to be very conservative about re-using descriptor sets - in most cases they would be immutable after creation, and only rewritten after we confirm that the last command buffer using them has been fully completed by the GPU.

**Comment by dati91** [comment]
So the proposed structure for this (via @kvark )
We should create a `DescriptorSet Pool` stored in `Device<B>`, and the pipeline will poll from it when needed.

The problem we try to solve:
Currently we store one descriptor set for each pipeline. And when a render pass uses the pipeline multiple times e.g. blur, when we use the same pipeline for horizontal and vertical blurs, the descriptor set will become invalid, is we want to change. Therefore we need to submit everything to the gpu before changing it.

The gpu submitting can be avoided if we instead of overriding the descriptor set, we (re)use one from the descriptor pool.

I checked and we use 51 pipelines. And those 51 uses 3 types of descriptor set:
- 7 image+sampler 1 ub, used by cs_clip_*, 5 of 51
- 4 image+sampler 1 ub, used by debug_*, 2 of 51
- 12 image+sampler 1 ub, used by everything else, 44 of 51
