### ISSUE TITLE
Add another shaders

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#12]
Add support for the following shaders:

**Primitive Shaders**
- [x] ps_rectangle
- [x] ps_rectangle_clip
- [x] ps_text_run
- [x] ps_text_run_subpixel
- [x] ps_image
- [x] ps_yuv_image
- [x] ps_border_corner
- [x] ps_border_edge
- [x] ps_gradient
- [x] ps_angle_gradient
- [x] ps_radial_gradient
- [x] ps_box_shadow*
- [x] ps_cache_image*
- [x] ps_blend*
- [x] ps_hw_composite*
- [x] ps_split_composite*
- [x] ps_composite*

**Cache Shaders**
- [ ] cs_box_shadow
- [ ] cs_text_run
- [ ] cs_blur

**Chache Clip Shaders**
- [ ] cs_clip_rectangle
- [ ] cs_clip_image
- [ ] cs_clip_border

`*` Not tested.

**Comment by dati91** [comment]
With `ps_rectangle` and `ps_border`:
![servo_wiki](https://cloud.githubusercontent.com/assets/2149430/25476311/112a7538-2b3a-11e7-9002-6c6c7900075f.png)

**Comment by zakorgy** [comment]
Borders with blending:
![borders](https://cloud.githubusercontent.com/assets/11725775/25488602/ba97f8b6-2b67-11e7-9cde-3ffe7e847866.png)

**Comment by dati91** [comment]
The `gradiant` shaders will require a different pipeline structure, because there is an additional `sGradients` sampler in the shaders.

**Comment by kvark** [comment]
> The gradient shaders will require a different pipeline structure, because there is an additional sGradients sampler in the shaders.

It is completely normal to have more PSO components defined than a particular shader uses. Thus, you could have an entry for `sGradients` and just bind a dummy resource view for the shaders that don't use it. No need for a different PSO definition.

**Comment by zakorgy** [comment]
We got some placeholder rectangles for text images and images.
![wr_gfx_text](https://cloud.githubusercontent.com/assets/11725775/25698211/3b640330-30be-11e7-9263-b08bde05e794.png)

**Comment by zakorgy** [comment]
@dati91 made progress with the texture implementation, we have now images and text.
![texture_update](https://cloud.githubusercontent.com/assets/11725775/25940612/006ef6f8-3637-11e7-80e2-c96b73055b89.png)

**Comment by dati91** [comment]
![gradient](https://cloud.githubusercontent.com/assets/2149430/25947740/fca567b8-3650-11e7-86ab-b21577895ae3.PNG)

**Comment by zakorgy** [comment]
Some new images with the current state
![wikipedia](https://user-images.githubusercontent.com/11725775/27329686-d1da8470-55b6-11e7-8dce-3d2db426493f.png)
:
![facebook](https://user-images.githubusercontent.com/11725775/27329656-bd4fa666-55b6-11e7-9ed3-e0fc1939dfdd.png)

**Comment by dati91** [comment]
clipping!

![wikipedia](https://user-images.githubusercontent.com/2149430/30160699-e046c7f8-93cd-11e7-83db-e29418b26d70.png)

![facebook](https://user-images.githubusercontent.com/2149430/30160684-d0a025c4-93cd-11e7-977c-cab96e61bfc5.png)

**Comment by dati91** [comment]
the same pages with directx 11!

![wikipedia](https://user-images.githubusercontent.com/2149430/30174244-afc26cc2-93fa-11e7-8f92-2f3a751b39c7.PNG)

![facebook](https://user-images.githubusercontent.com/2149430/30174251-b567fc96-93fa-11e7-96fc-09d9ecb6b0d8.PNG)
