### ISSUE TITLE
Dual source blending on Intel crashes

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#136]
With [this](https://github.com/szeged/webrender/pull/132) we enabled [dual source blending](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#framebuffer-dsb).
This is crashing on windows (Intel driver). It works (or at least not crashing) on linux.
It seems like a driver bug, because I am not the only one with this.
https://software.intel.com/en-us/forums/graphics-driver-bug-reporting/topic/748226

**Comment by kvark** [comment]
Looks like it is expecting a non-NULL structure being passed in. Could you try providing all the input fields with default/zero structs?

**Comment by dati91** [comment]
I checked it and couldn't found anything.
Also tested it with a pure c++/vulkan test and it also crashed.

But I found one missing thing from gfx-rs that we will need:
```
ERROR:: [DS] Object: 0x163b | CmdBindPipeline: vkPipeline (0x163b) attachment[0] has a dual-source blend factor but this device feature is not enabled.
```
We need to pass the `dual-source blending` flag to the [DeviceCreation](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VkDeviceCreateInfo).

I tested it with the following code, replacing [this](https://github.com/gfx-rs/gfx/blob/21a82392ff1cccff35b087114d33b2e25e358068/src/backend/vulkan/src/lib.rs#L352) line.
```
let mut enabled_features = vk::PhysicalDeviceFeatures::default();
enabled_features.dual_src_blend = vk::VK_TRUE;
```
It got rid of the validation error, but the crash still happens.

**Comment by kvark** [comment]
Upstream issue: https://github.com/gfx-rs/gfx/issues/1928
We might need to start blacklisting particular drivers/HW...

**Comment by kvark** [comment]
Ok, a simple Vulkan black list is in place. You should get the proper capabilities after another gfx-rs update.

**Comment by dati91** [comment]
For testing: https://github.com/dati91/gfx/commit/d8b37f0b51c2bb5b2ab3de7dc3ab1305e3d7a1c6

**Comment by dati91** [comment]
I'm closing this, since it was handled in gfx.
