### ISSUE TITLE
Border corner is missing when rotated

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#156]
```
reftests/transforms/border-zoom.yaml
```
![border-zoom yaml](https://user-images.githubusercontent.com/2149430/39368384-b7b0f624-4a39-11e8-93a2-bea88ce429a3.png)
```
reftests/transforms/prim-suite.yaml
```
![prim-suite yaml](https://user-images.githubusercontent.com/2149430/39368400-c1f17226-4a39-11e8-9e29-395fa8846851.png)

The problem only occurs when we use the `transform` variant of the `ps_border_corner`.
In renderdoc it seems like the vertex shader produces the same results as the original gl webrender.

The only difference in the fragment shader is [this](https://github.com/szeged/webrender/blob/master/webrender/res/ps_border_corner.glsl#L343) alpha value.
Not sure what causes this behavior because the `ps_border_edge` uses the same logic and the edges are drawn.
Also if I remove the `alpha *= do_clip();` after the `init_transform_fs` the corners appear perfectly.
Which is strange, because the `do_clip` should return 1.0, which won't change a thing. (Or at least the `vClipMaskUvBounds` is `[0.0, 0.0, 0.0, 0.0]` in renderdoc)

**Comment by kvark** [comment]
What does the pixel history say (from RenderDoc)?

**Comment by dati91** [comment]
> What does the pixel history say (from RenderDoc)?
"Pixel History not implemented on this API"

**Comment by dati91** [comment]
![border_corner_bug](https://user-images.githubusercontent.com/2149430/39635448-d6d7de08-4fbd-11e8-9404-f60b88850e61.gif)

If I run it with `wrench show`, there is an artifact in the upper left corner (very rarely).

**Comment by dati91** [comment]
So I [changed](https://gist.github.com/dati91/340ec798d3a7e927cef5e54e75602099) the order of the `init_transform_fs` and `do_clip` which shouldn't change a thing in this case, but we got the expected result.
![border-zoom yaml](https://user-images.githubusercontent.com/2149430/39639245-f9ec04c2-4fc8-11e8-8613-49bc07094fda.png)

**Comment by dati91** [comment]
Updating the VulkanSDK solved this issue.
