### ISSUE TITLE
Too many vertex attributes used by shaders

### ISSUE THREAD

**Issue by zakorgy** [szeged/webrender#180]
I ran in the following vulkan validation layer errors, while doing a rebase:
```
ERROR: [Validation] Object: VK_NULL_HANDLE (Type = 0) | vkCreateGraphicsPipelines: parameter pCreateInfos[0].pVertexInputState->pVertexAttributeDescriptions[5].location (16) is greater than or equal to VkPhysicalDeviceLimits::maxVertexInputAttributes (16). The spec valid usage text states 'location must be less than VkPhysicalDeviceLimits::maxVertexInputAttributes' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkVertexInputAttributeDescription-location-00620)
ERROR: [Validation] Object: VK_NULL_HANDLE (Type = 0) | vkCreateGraphicsPipelines: parameter pCreateInfos[0].pVertexInputState->pVertexAttributeDescriptions[6].location (17) is greater than or equal to VkPhysicalDeviceLimits::maxVertexInputAttributes (16). The spec valid usage text states 'location must be less than VkPhysicalDeviceLimits::maxVertexInputAttributes' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkVertexInputAttributeDescription-location-00620)
ERROR: [Validation] Object: VK_NULL_HANDLE (Type = 0) | vkCreateGraphicsPipelines: parameter pCreateInfos[0].pVertexInputState->pVertexAttributeDescriptions[7].location (18) is greater than or equal to VkPhysicalDeviceLimits::maxVertexInputAttributes (16). The spec valid usage text states 'location must be less than VkPhysicalDeviceLimits::maxVertexInputAttributes' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkVertexInputAttributeDescription-location-00620)
ERROR: [Validation] Object: VK_NULL_HANDLE (Type = 0) | vkCreateGraphicsPipelines: parameter pCreateInfos[0].pVertexInputState->pVertexAttributeDescriptions[8].location (19) is greater than or equal to VkPhysicalDeviceLimits::maxVertexInputAttributes (16). The spec valid usage text states 'location must be less than VkPhysicalDeviceLimits::maxVertexInputAttributes' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkVertexInputAttributeDescription-location-00620)
ERROR: [Validation] Object: VK_NULL_HANDLE (Type = 0) | vkCreateGraphicsPipelines: parameter pCreateInfos[0].pVertexInputState->pVertexAttributeDescriptions[9].location (20) is greater than or equal to VkPhysicalDeviceLimits::maxVertexInputAttributes (16). The spec valid usage text states 'location must be less than VkPhysicalDeviceLimits::maxVertexInputAttributes' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkVertexInputAttributeDescription-location-00620)
```
The number of non uniform variables in the new `cs_border_segment` shader exceeded the limit(16), the shader has 20. We should change the numbering in the build script if possible, or reduce the number of the parameters in the shader.
NOTE: The `cs_border_segment` shader contains `aData0` and `aData1` variables, but doesn't use it. Also we have to bind a value for these variables like we did with the [BlurInstance](https://github.com/szeged/webrender/blob/master/webrender/src/device.rs#L196).

**Comment by zakorgy** [comment]
https://github.com/servo/webrender/pull/2784 decreased the total number of vertex attributes in the generated `cs_border_segment` shaders. There is now 17 of them (previously we had 21), but we should have only 16. When the transition of border shaders is finished in the upstream WR, we can revisit this issue, and figure out something if the number of  vertex attributes is still greater than 16. Until then there is a workaround (https://github.com/szeged/webrender/commit/09b5e3fb1419576108a22b63c647eabed7abff5f, https://github.com/szeged/webrender/commit/0cbd127a64b82e8ad7191bd5c361b4870f66a920) for the validation layer error on our local branch.

**Comment by gw3583** [comment]
I'm not sure where the extra attributes are coming from - could you list the attribute names?

https://github.com/servo/webrender/blob/5e4f257d9f3cdb5691ac62f3affe2e9189d66447/webrender/res/cs_border_segment.glsl#L60

As of #2784 the shader has 7 input attributes, and it includes shared.glsl which has 1 attribute, and ellipse.glsl which has 0 attributes. Are there extra ones coming from somewhere else?

I'll shortly be opening a new PR which adds two more attributes to this shader so it'd be good to work out what's causing this issue :)

**Comment by dati91** [comment]
So i just checked the shader and our build script, and i think i know what can be the problem.
We parse the shader file from the beginning and the varying attributes will get location numbers as well, and when we reach the actual in attributes, the location numbers will exceed the supported limit.

**Comment by gw3583** [comment]
Ah, that makes sense. So should we close this bug? (is there anything we need to do in WR for it?)

**Comment by kvark** [comment]
@dati91 it definitely doesn't make sense to mix the vertex attributes with vertex varying in the same namespace, anyway, so I'm closing the upstream issue, but we can keep this one open.
