### ISSUE TITLE
Concatenate shaders from WebRender

### ISSUE THREAD

**Issue by loki04** [szeged/webrender#2]
- [x] Examine how the primitive shaders work
- [x] Concatenate primitive shaders to have everything in build time
- [x] Compare The Validator of ~~Servo~~ Webrender if it can be used for the concatenation

**Comment by zakorgy** [comment]
https://github.com/zakorgy/webrender/commits/dati_gfx_device contains the shader concatenation.

**Comment by dati91** [comment]
Done: https://github.com/szeged/webrender/pull/7
