### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#21]
We facing a strange behavior, which looks like some kind of (hard?) limit.
It can be reproduced with the following [test](https://gist.github.com/anonymous/ed82513966b494685a43a70486306c1c).
We draw 20 x 20 green rect (every fifth row is yellow), the we draw 20x20 red rect next (400.0 offset) to our first rects.
Original result: 
![rect_wr](https://cloud.githubusercontent.com/assets/2149430/26825070/f076219a-4ab3-11e7-9f11-909461bd7bba.png)

With our code it looks like this:
![rect_gfx](https://cloud.githubusercontent.com/assets/2149430/26825154/3f713096-4ab4-11e7-8d17-e4dbfd96318c.png)

Some observation:
* It only draws the first __256__ rects (a strange coincidence?)
  * and without drawing the red rects it still just 256
* If we draw the red rects it starts from the where we finished our green/yellow rects
  * it should start from the top (with x + 400 offset)
  * and it draws 256 red rects

So it looks like to me there is a u8::max (0..255) hard limit somewhere.
Or (more likely?) our texture width size (4*256=1024) has something to do with it.

**Comment by dati91** [comment]
Increasing our `prig_geo`'s __row__ length definitely helped our case:
![rect_gfx_prim_geo](https://cloud.githubusercontent.com/assets/2149430/26829848/3a4bc1c2-4ac7-11e7-9b05-44dd89c432bf.png)

**Comment by kvark** [comment]
So the new code that samples from the primitive geometry texture is not correct then?
