### ISSUE TITLE
Regression with dx12 after the latest gfx update

### ISSUE THREAD

**Issue by zakorgy** [szeged/webrender#224]
Before the [update](8453f2682b1107e6d198197a27017c4c8af184ca) we had `REFTEST INFO | 220 passing, 7 failing` with `dx12`, now we have `REFTEST INFO | 174 passing, 53 failing` with `wrench` and `dx12`.
We have blank results, in some cases.
Right now I can't tell what causes this, because if I capture one of these tests with RenderDoc the capture window is empty, but the Textur Viewer and Mesh Output show the expected result.  I will continue investigating this.
The debug layer doesn't show any error in DebugView.

**Comment by kvark** [comment]
cc @msiglreith

**Comment by msiglreith** [comment]
I tested https://github.com/szeged/webrender/commit/f31f31104712f3ea4a681c98c9783bfb788a0425 but don't see any difference for the `blob` example compared to master. Do know a revision which worked?

**Comment by dati91** [comment]
I checked the issue again:
The blob example with https://github.com/szeged/webrender/commit/f31f31104712f3ea4a681c98c9783bfb788a0425
![blob_dx12](https://user-images.githubusercontent.com/2149430/46789527-ea73f580-cd3c-11e8-884a-a729d97f18a7.PNG)
The blob example with https://github.com/szeged/webrender/commit/8453f2682b1107e6d198197a27017c4c8af184ca
![blob_dx12_new](https://user-images.githubusercontent.com/2149430/46789618-2c9d3700-cd3d-11e8-8f11-714dd67a6793.PNG)
When I capture it with RenderDoc, on the capture it shows the empty window
![blob_rd1](https://user-images.githubusercontent.com/2149430/46789650-40489d80-cd3d-11e8-8871-32c71398ea98.PNG)
But if I change to the Texture Viewer tab, it shows the correct drawing
![blob_rd2](https://user-images.githubusercontent.com/2149430/46789733-7dad2b00-cd3d-11e8-9e29-44fb45e6d9bc.PNG)

Also I checked this on my laptop (nvidia card), and the result is correct with our latest master. So it can be driver related. Most probably our Intel driver is not that permissive, wouldn't be the first time.

**Comment by kvark** [comment]
@msiglreith do you have an Intel iGPU machine by any chance to test this?

**Comment by msiglreith** [comment]
@kvark no only a desktop AMD gpu. I tried PIX and VS Graphics Debugger for capturing but no sucess, with renderdoc I was able to capture it but it crashes once I try to inspect a draw call. In both revisions I only see the cleared screen.

**Comment by dati91** [comment]
@kvark @msiglreith The problem is here:
https://github.com/gfx-rs/gfx/blob/bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7/src/backend/dx12/src/command.rs#L586-L608

When it changed to d3d12, the rect.len check disappeared,
The clear_render_target_view still uses the original code, and the null check is there:
https://github.com/gfx-rs/gfx/blob/bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7/src/backend/dx12/src/command.rs#L572-L577

Since the call is now in d3d12, the check should be here:
https://github.com/gfx-rs/d3d12-rs/blob/6369df29e81cf94fa15d94ab4290bc775b70f68e/src/command_list.rs#L91-L109

And my guess is that the clear_render_target_view also needs this in d3d12.

**Comment by msiglreith** [comment]
That check is actually not required in this location as vulkan doesn't allow zero-length ranges.

**Comment by zakorgy** [comment]
We can close this, since it's fixed in gfx-rs now (https://github.com/gfx-rs/gfx/commit/87474c4c7fe7ecdf87d965875c70e4db4983be09)
