### ISSUE TITLE
update readme to include information about gfx-hal backend?

### ISSUE THREAD

**Issue by bzm3r** [szeged/webrender#275]
Could the readme be updated to reflect that this fork contains WIP implementing a gfx-hal backend for webrender? Perhaps with some information regarding where the work has reached so far?

**Comment by zakorgy** [comment]
Hi @bzm3r! I have added a small description in https://github.com/szeged/webrender/pull/276 .

**Comment by bzm3r** [comment]
@zakorgy thank you!
