### ISSUE TITLE
Frame profiler not working

### ISSUE THREAD

**Issue by SergeevPavel** [szeged/webrender#278]
Frame profiler not showing when I enable `DebugFlags::PROFILER_DBG`.
Particularly it happens in examples, when I use metal backend. With gl it works fine.

**Comment by zakorgy** [comment]
It looks like something went wrong during the latest rebase, and `DebugRenderer` doesn't work with `gfx-hal` backend. @SergeevPavel thanks for the report, I will take a look at that.

**Comment by zakorgy** [comment]
@SergeevPavel  I have started to addressing this in https://github.com/szeged/webrender/pull/279.

**Comment by zakorgy** [comment]
Fixed by #279
