### ISSUE TITLE
WR can overflow

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#29]
Storing too much data can overflow. In our case we use for a (`primitive`) shader (which can be either `simple` or `transform`) 4 psos for blending with 2 variant for `depth write`.

`ps_rectangle` = type x blend x depth= 2 x 4 x 2 = 16 psos
And we use 22 primitive shaders (352 psos) and 6 other shaders (9 psos).

On a low/medium-end PC this can cause an overflow.
On a high-end it can be reproduced with this patch: https://github.com/dati91/webrender/commit/374b360159e57c877d43f1722c0b301d5f666dc1

The error:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555a28581 in webrender::renderer::Renderer::new (window=<error reading variable: Cannot access memory at address 0x7fffff375cd0>,
    options=<error reading variable: Cannot access memory at address 0x7fffff375ce0>,
    initial_window_size=<error reading variable: Cannot access memory at address 0x7fffff375d58>) at src/renderer.rs:705
705         pub fn new(window: Rc<window::Window>,
```

**Comment by kvark** [comment]
I looked over the code and didn't see any large fixed-size arrays on the stack for programs/PSOs. Would be interesting to investigate this by printing out `size_of` of your `Program` as well as it's components.

A simple workaround would be to `Box` programs.

**Comment by zakorgy** [comment]
Fixed by: https://github.com/zakorgy/webrender/commit/ccd1f67d204105902177cbe2c8feb23b8b91545c

**Comment by kvark** [comment]
@zakorgy now that I think of it, the issue could be solved by having `create_programs`, `create_clip_program`, and such returning `Box<>` as opposed to trying to box it after the fact. This is a simpler change not requiring rust nightly.

**Comment by zakorgy** [comment]
@kvark thank you, this works well for us.
