### ISSUE TITLE
Investigate WebGL

### ISSUE THREAD

**Issue by loki04** [szeged/webrender#3]
- [ ] Check if it is possible to render WebGL with the current implementation to offscreen and draw with Gfx_rs on the screen
- [ ] Adopt a preliminary implementation in WebRender

**Comment by zakorgy** [comment]
WebGL contexts are already rendered to off-screen with the `rust-offscreen-rendering-context` trait and are represented as a special image primitive. This primitive contains the context id and the canvas rectangle coordinates, and it gets resolved when building a frame.
`rust-offscreen-rendering-context` uses GLContext wrapper structure around the native off-screen OpenGL context. A Frame Buffer Object for the off-screen context is accessible trough this wrapper with the `get_framebuffer` call, and we can get the required pixel data from this buffer object with `read_pixels`.
In webrender the `RendererBackend` structure contains all the webgl contexts in a map. Using this map, we can get the pixel data for each webgl context, and make a texture from it for each frame.
`RenderBackend` communicates with the `RenderApi` trough IPC and receiving the `ApiMsg::GenerateFrame` builds the frame, and in most cases, this is where the WebGL textures are updated.

**Comment by zakorgy** [comment]
Here is an example ,where we render the content of a WebGL context as a dynamic texture in a separete window. Unfortunately the drawing in the second window is slow, we think this is mainly because of the `encoder.update_texture` call. But changing the texture creation may speed up this process.
https://github.com/zakorgy/webrender/commits/webgl-with-gfx-test

**Comment by zakorgy** [comment]
In https://github.com/zakorgy/webrender/commit/13f0bcfc7c7c6e2a7a925de65c31dec99a148f42 we read the WebGL pixels for each frame, and draw it as a texture in the webrender window with gfx backend.
This gif shows the performance difference running the same WebGL code in the webrender (left window) and with the solution described above(right): https://gifyu.com/image/SXWd .
For this we extended the webrender sample (sample/src/main.rs) with a simple WebGL part.
This is just an experiment, to see we can render the WebGL using gfx backend. Impelementing the `ps_image` shader hopefully will solve this issue.

**Comment by zakorgy** [comment]
This can be closed because webrender no longer needs WebGL: https://github.com/servo/webrender/commit/5b12aced1a41a8fcb1c2ebdd3412f49ec5065627
