### ISSUE TITLE
Reftest regression with gfx-backend-metal 0.3.3

### ISSUE THREAD

**Issue by zakorgy** [szeged/webrender#309]
`reftests/split/nested-preserve3d-crash.yaml` reftest fails with when running all the reftests (otherwise it passes):
`REFTEST TEST-UNEXPECTED-FAIL | reftests/split/nested-preserve3d-crash.yaml == reftests/split/nested-preserve3d-crash.yaml | image comparison, max difference: 255, number of differing pixels: 19194`.
The issue was introduced in f488584114728b5bc7745460442e7fc5df9a7f81, which is a gfx-rs update.
The previous version of `gfx-backend-metal` was `0.2.0`.
The images from the base64 output:
Result:
![cbimage](https://user-images.githubusercontent.com/11725775/64607437-cf848800-d3c8-11e9-838c-272329571fd9.jpg)

Reference:
![cbimage-2](https://user-images.githubusercontent.com/11725775/64607440-d14e4b80-d3c8-11e9-9de1-8edb3ebe9699.jpg)

**Comment by kvark** [comment]
Interesting, thanks for the investigation!
Would you be able to provide a Metal GPU capture?

**Comment by zakorgy** [comment]
11e3f61060c6c83d455e456f2bac4fc1abe4b873 introduced new fails with metal backend:
- [ ] reftests/blend/multiply-2.yaml == reftests/blend/multiply-2-ref.yaml
- [ ] reftests/blend/difference.yaml == reftests/blend/difference-ref.yaml
- [ ] reftests/blend/difference-transparent.yaml == reftests/blend/difference-transparent-ref.yaml
- [ ] reftests/blend/darken.yaml == reftests/blend/darken-ref.yaml
- [ ] reftests/blend/lighten.yaml == reftests/blend/lighten-ref.yaml
- [ ] reftests/blend/repeated-difference.yaml == reftests/blend/repeated-difference-ref.yaml
- [ ] reftests/blend/isolated-2.yaml == reftests/blend/isolated-2-ref.yaml
- [ ] reftests/filters/filter-mix-blend-mode.yaml == reftests/filters/filter-mix-blend-mode-ref.yaml

these are blending related

**Comment by zakorgy** [comment]
The fails in https://github.com/szeged/webrender/issues/309#issuecomment-542669184 were fixed in #323 and the fails in https://github.com/szeged/webrender/issues/309#issue-491595364 seems to be absent with our latest version (c9a99e4f3b2397cbd3fe59159d572bf5a91ba895).
