### ISSUE TITLE
Support Android backend

### ISSUE THREAD

**Issue by fokinv** [szeged/webrender#31]
The goal is to make gfx backend work on Android

**Comment by fokinv** [comment]
After building for android, Servo crashes with:
```
D/RustAndroidGlueStdouterr( 4572): Error InvalidEnum executing command: SetRasterizer(Rasterizer { front_face: CounterClockwise, cull_face: Back, method: Fill, offset: None, samples: None }) (thread <unnamed>, at /media/fokinv/45504fcc-c4bb-4ab4-914d-b04361e2341f/Work/Mozilla/szeged_servo_android/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.14.3/src/lib.rs:768)
```
I used: 
- Servo:
https://github.com/szeged/servo/commit/2fce36b0053a8a7837aa119f8a489b2eccafcd39
with this 
https://gist.github.com/dati91/a40d15f6e66cd018603a84da2d13137f
- Webrender:
https://github.com/szeged/webrender/tree/dx11
- gfx:
https://github.com/zakorgy/gfx/tree/dx11

**Comment by kvark** [comment]
I believed we fixed it in `gfx_device_gl` 0.14.4 (see https://github.com/gfx-rs/gfx/pull/1488)

**Comment by fokinv** [comment]
We got the previous error with a board and currently I can't check if it works, yet. On another device (S8) we got an other error:
```
RustAndroidGlueStdouterr: called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } } (thread <unnamed>, at /checkout/src/libcore/result.rs:860)
```

**Comment by fokinv** [comment]
I got past the `No such file or directory` by adding the shader file to the `apk` and I used the `default_config_dir()` function, just like in servo's `main.rs` to load the shaders in `renderer.rs`.
After that there was a `called unimplemented OpenGL ES API` error, which was caused by `sync(&mut mapping);` call in gfx/src/core/src/mapping.rs, I only found it implemented in metal backend.
And when I commented the function call out, I got `libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 32007 (m.mozilla.servo)` error.

**Comment by kvark** [comment]
Thanks @fokinv , filed as https://github.com/gfx-rs/gfx/issues/1499, hold tight!

**Comment by kvark** [comment]
Hmm, mapping should still work on ES3 devices. Are you trying to run it on an ES2 one? This is not going to work, I'm afraid. WR's current min spec is ES-3.1 IIRC (and even though it would be nice to lower this requirement, you see where this is going).

**Comment by dati91** [comment]
We are using a Samsung Galaxy S8 phone.

**Comment by fokinv** [comment]
When we change the version of the Shaders to 310 we got an other error: 
```
gl function was not loaded (thread <unnamed>, at /media/fokinv/45504fcc-c4bb-4ab4-914d-b04361e2341f/Work/Mozilla/szeged_servo_android/target/armv7-linux-androideabi/debug/build/gfx_gl-15c7fd5127b4e8d8/out/gl_bindings.rs:1504)
ERROR:servo: gl function was not loaded
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7 in tid 31131 (Thread-2)
```
I traced it back to `src/backend/gl/src/state.rs`. In the function `pub fn bind_blend_slot(gl: &gl::Gl, slot: ColorSlot, color: s::Color)` there's this call, which causes the crash:
```
gl.BlendEquationSeparateiARB(buf,
    map_equation(b.color.equation),
    map_equation(b.alpha.equation)
);
```

**Comment by fokinv** [comment]
@kvark 
Is it because we need to enable some extension in the shader files, or is it some other problem?
