### ISSUE TITLE
Unexpected wrench result with border images

### ISSUE THREAD

**Issue by zakorgy** [szeged/webrender#32]
Running the border image related reftests (border-image.yaml and border-image-fill.yaml) display the expected results , but the tests are failing, because the pixel data we get with readpixels is different from what we see in the window.
Here is a screenshot from the running border-image test:
![glutin](https://user-images.githubusercontent.com/11725775/32328384-1dbd72ac-bfda-11e7-8a5c-236583f40a82.jpg)
The expected result:
![border-image-ref](https://user-images.githubusercontent.com/11725775/32328637-d90055c0-bfda-11e7-9773-6d6d8dc99856.png)
And the debug image result from wrench:
![read_pix](https://user-images.githubusercontent.com/11725775/32328466-5b2c0374-bfda-11e7-9fe9-b6621ed615aa.jpg)

**Comment by kvark** [comment]
For the repro instructions, which branch is to use?

**Comment by zakorgy** [comment]
@kvark we used the refactor_44_to_50 branch here (https://github.com/szeged/webrender/tree/refactor_44_to_50). I recommend to use it on linux, because I'm not sure, that wrench builds on windows with the cfg-s we use in it.

**Comment by kvark** [comment]
The color is actually there, but the alpha written is 0. Either this is a bug with the shader, color mask, or you just need to tweak the image readback function to overwrite alpha with 0xFF, e.g.
```rust
                    output[offset + 0] = src[0];
                    output[offset + 1] = src[1];
                    output[offset + 2] = src[2];
                    output[offset + 3] = 0xFF; // <-- alpha
```

**Comment by zakorgy** [comment]
As it turned out, this was caused by the conversion to rgba data in our implementation. We set the alpha values to zero incorrectly. Fixed here: https://github.com/szeged/webrender/commit/b4228abbe7d1fe0894f77dccd6ee07ab9ad5d1e4
