### ISSUE TITLE
wrench reftest crashed when using Metal backend

### ISSUE THREAD

**Issue by hellotanuky** [szeged/webrender#326]
OS: macOS 10.15.1

run `RUST_BACKTRACE=1 cargo run --features=metal reftest`

crashlog:
https://gist.github.com/hellotanuky/e0659445372f75498dfe2b7ef7cab500

and macOS problem report:
https://gist.github.com/hellotanuky/3d8a8aaaac89c9440726e9204259b93b

**Comment by zakorgy** [comment]
@hellotanuky thanks for reporting this. I think the problem is that we don't take hidpi in account, we assume it's always set to `1.0`. I will fix that, and let you know when I'm done.

**Comment by hellotanuky** [comment]
Another question: How can I test it in Firefox? I tried replace gfx/wr folder with this repo and run `mach build` but it failed with following log.
```
0:07.58 error: no matching package named `gfx-hal` found
0:07.58 location searched: registry `https://github.com/rust-lang/crates.io-index`
0:07.58 required by package `webrender v0.60.0 (/Users/nil/Park/ff/mozilla-unified/gfx/wr/webrender)`
0:07.58     ... which is depended on by `webrender_bindings v0.1.0 (/Users/nil/Park/ff/mozilla-unified/gfx/webrender_bindings)`
0:07.58     ... which is depended on by `gkrust-shared v0.1.0 (/Users/nil/Park/ff/mozilla-unified/toolkit/library/rust/shared)`
0:07.58     ... which is depended on by `gkrust v0.1.0 (/Users/nil/Park/ff/mozilla-unified/toolkit/library/rust)````

**Comment by zakorgy** [comment]
I have a branch for connecting this WR with gecko, but I still need to fix some things to properly build on macOs. I will link the branch here for you tomorrow, after everything is in place.

**Comment by hellotanuky** [comment]
Thank you!

**Comment by zakorgy** [comment]
@hellotanuky here is the gecko branch which I was talking about: https://github.com/zakorgy/gecko-dev/commits/ff_77_0a1_gfx
