### ISSUE TITLE
Compile shaders to spir-v

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#5]
Vulkan requires spir-v format, which we can compile at build time.

Depends on: #2

**Comment by zakorgy** [comment]
The code for this os on the spirv-support branch [here](https://github.com/szeged/webrender/commit/d70bd34494273d87b0675fa87aca441302ac869a#diff-750292e41b0bfa8da2a228dc6b5843edR230), and the spir-v binaries are validated with `spirv-val` .
