### ISSUE TITLE
DX12 Shader compilation error

### ISSUE THREAD

**Issue by zakorgy** [szeged/webrender#53]
Running with dx12 fails with "Combined image samplers have no default expression representation.",  when running SPIRV_Cross. This points here:
https://github.com/KhronosGroup/SPIRV-Cross/blob/ab3907e4b59b243e7391a71f5e962c1bb5ab8451/spirv_glsl.cpp#L2299

**Comment by kvark** [comment]
Could you please file this issue to us at gfx-rs and provide the failing GLSL (or SPIRV) shader?

**Comment by dati91** [comment]
With the latest [spirv_cross crate ](https://crates.io/crates/spirv_cross/0.4.6) we managed to pass the previous issue.

And managed to run into one of our last years issue with hlsl, that it can't handle this kind of return types:
https://github.com/szeged/webrender/blob/master/webrender/res/prim_shared.glsl#L55
It fails with the following error:
```
error X3000: syntax error: unexpected token {
error X3017: cannot implicitly convert from const float4 to float4[2]
```

The `vec4[2]` should be converted to `float4x2`. ( https://msdn.microsoft.com/en-us/library/windows/desktop/bb509623(v=vs.85).aspx )

Note: We could do a workaround for that (as we previously did), to replace the vec4[X] with a structure.

**Comment by grovesNL** [comment]
I created KhronosGroup/SPIRV-Cross/issues/428 with a small test case

**Comment by zakorgy** [comment]
I added out array parameters to the above mentioned functions also replaced their return type to void here: https://github.com/zakorgy/webrender/tree/dx12. This fails with the following error: 
```
ERROR:gfx_backend_dx12::device: D3DCompile error 80004005
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Shader(CompilationFailed("C:\\Users\\zakorgy\\work\\webrender_newgen\\webrender\\Shader@0x00000268FE45FF70(233,28): error X3000: syntax error: unexpected token \'{\'\n\u{0}"))',
```
I compiled one of the generated spirv shader with spirv-cross to [hlsl](https://gist.github.com/zakorgy/3f04ca15ece2e703b16465052693fea9#file-ps_border_corner-vert-hlsl), and it looks like the problem is, that the assignment in [line 233](https://gist.github.com/zakorgy/3f04ca15ece2e703b16465052693fea9#file-ps_border_corner-vert-hlsl-L233) is not valid syntactically:
```
 ClipArea area;
    if (index == 2147483647)
    {
        area.common_data = { { 0.0f.xx, 0.0f.xx }, 0.0f };
        area.screen_origin = 0.0f.xx;
    }
```
This should be something like this:
```
 ClipArea area;
    if (index == 2147483647)
    {
        RectWithSize rect = { 0.0f.xx, 0.0f.xx };
        RenderTaskCommonData common_data = {rect, 0.0f};
        area.common_data = common_data;
        area.screen_origin = 0.0f.xx;
    }
```

**Comment by kvark** [comment]
Initialization bug is filed in https://github.com/KhronosGroup/SPIRV-Cross/issues/440

**Comment by zakorgy** [comment]
@kvark meanwhile I found another issue. `fxc` complains about the missing default branches in switch statements, and fails with  `Not all control paths return a value`.

**Comment by kvark** [comment]
@zakorgy sounds like something we should fix upstream. Having unexpected values triggering UB in the shaders is not good, the cost of trapping those values shouldn't be high.

**Comment by kvark** [comment]
Added https://github.com/servo/webrender/wiki/Driver-issues#lack-of-default-case-in-a-switch

**Comment by kvark** [comment]
Should be fixed by https://github.com/servo/webrender/pull/2414

**Comment by zakorgy** [comment]
Nice. Thank you @kvark.

**Comment by dati91** [comment]
I think we can close this.
