### ISSUE TITLE
Implement Textures

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#6]
Replace the current implementation with with gfx's textures (surface, sampler, view).
[gfx_texture](https://github.com/PistonDevelopers/gfx_texture/) from PistonDevelopers is a good starting point.

**Comment by dati91** [comment]
More info: http://gfx-rs.github.io/2016/09/14/programming-model.html#resource-views

**Comment by dati91** [comment]
Webrender's blob example:
![blob](https://cloud.githubusercontent.com/assets/2149430/25940729/5b61bece-3637-11e7-82d7-e7405b108ea7.PNG)

**Comment by kvark** [comment]
I wouldn't recommend using piston's `gfx_texture` crate. It's only useful if you use the Piston engine itself. Taking the code for the reference is fine though.

**Comment by dati91** [comment]
Yes, we didn't use their crate, just the logic.
