### ISSUE TITLE
Segfault on windows

### ISSUE THREAD

**Issue by zakorgy** [szeged/webrender#65]
The current master(b04d40a2550d021f82ec0a23dc33a876e630bfe2) causes a segfault when running some of the wrench reftests, e.g. `border-suite-2.yaml` or `reftests\aa\rounded-rects.yaml`
platform: windows

**Comment by zakorgy** [comment]
After a git bisect, looks like the changes introduced in 738b821d87b27d1f282a4601cd5c22e8a5a0cc4f cause the segfault on windows.

**Comment by kvark** [comment]
Please provide a stack trace.

**Comment by zakorgy** [comment]
Unfortunately we can't get the stack trace with `RUST_BACKTRACE` or gdb, only the segfault message is shown.

**Comment by zakorgy** [comment]
Looks like the source of the problem is, that we want to draw an R8 texture, but we only support Rgba8Unorm as surface format in our RenderPass on windows.

**Comment by zakorgy** [comment]
I tried to fix this [here](https://github.com/zakorgy/webrender/commits/win-segfault) by creating a new renderpass for R8 textures, but it didn't resolve the issue.
