### ISSUE TITLE
Buffer offset incorrect behavior

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#71]
I started look into the remaining failing tests and our first issue is that we use our instance buffers totally wrong.

Currently we bind the instances and call draw, but if we use the same program again, we will overwrite the current buffer.

Should be an easy fix. :crossed_fingers:

**Comment by dati91** [comment]
Finally figured out an other related issue, which results in drawing with the incorrect transform matrix.
Like we did we with the instance buffer, we only use one local buffer with 0 offset only.
And if we use the pipeline again with a different transform, we override the previous one.

**Comment by dati91** [comment]
The `uniform buffer` issue is still exists, most probably we will need `dynamic uniform buffers` or as a workaround a `push_constant` solution.

**Comment by kvark** [comment]
The problem with uniform buffer updates is also reported by validation layers:
> RDOC 015177: [10:01:48]          vk_core.cpp(2620) - Warning - [DS:1676/9] You are adding vkQueueSubmit() to command buffer 0x0x7fae7a7bdc00 that is invalid because bound DescriptorSet 0x11c was destroyed or updated.

We can't just update a descriptor sets between issuing command buffer calls. We need to either use push constants, or create new descriptor sets when the data is changed (potentially, pooling/caching the old ones) and bind the new ones where needed.

Really though, we need to get through those validation layers and address them.
