### ISSUE TITLE
Run WebRender with DX12

### ISSUE THREAD

**Issue by zakorgy** [szeged/webrender#73]
The following steps are required
- [x] Rebase to the current upstream WebRender, for the shader updates. (I cherry-picked them for now)
- [x] Change array return types in shaders to out parameters (I have a patch for this on my working [branch](https://github.com/zakorgy/webrender/commits/dx12)): 
https://github.com/zakorgy/webrender/commit/ee7cbf206e0dfb155c72ee3b2ef0f8b164cecdc8

- [x] D2Array is not supported in gfx-rs yet: https://github.com/gfx-rs/gfx/blob/8d0ef5ba96bb4a2ecc5671975677323f11773dc5/src/backend/dx12/src/device.rs#L609,
we fallback to D2 texture for now: https://github.com/zakorgy/webrender/commit/c494908717c6c7d5086ae42832ac11e2a6d7cd38

- [x] Find out why the `copy_buffer_to_image` fails on the assert here: https://github.com/gfx-rs/gfx/blob/8d0ef5ba96bb4a2ecc5671975677323f11773dc5/src/backend/dx12/src/command.rs#L1289
When runing the `basic_hal` example the third  `copy_buffer_to_image` call fails with values: `buffer_width = 240, width = 1020` because `buffer_width` should be greater or equal than `width`. 
The other strange thing is, that the previous two `copy_buffer_to_image` also generates errors with the debug layer  turned on. Here is a DebugView capture for this:
```
00000001	0.00000000	[9276] D3D12 ERROR: ID3D12CommandList::CopyTextureRegion: The region specified by D3D12_TEXTURE_COPY_LOCATION:PlacedFootprint extends past the end of the buffer it is placed on. The size required by PlacedFootprint is 536641536, as the fields of PlacedFootprint::Placement are as follows: RowPitch is 262144, Height is 2048, and Format is R32G32B32A32_FLOAT. PlacedFootprint::Offset is 0, which requires the buffer to have 536641536 bytes; but the buffer only has 67108864 bytes. [ RESOURCE_MANIPULATION ERROR #869: COPYTEXTUREREGION_INVALIDSRCPLACEMENT]	
00000002	0.00087751	[9276] D3D12 ERROR: ID3D12CommandList::CopyTextureRegion: The region specified by D3D12_TEXTURE_COPY_LOCATION:PlacedFootprint extends past the end of the buffer it is placed on. The size required by PlacedFootprint is 536641536, as the fields of PlacedFootprint::Placement are as follows: RowPitch is 262144, Height is 2048, and Format is R32G32B32A32_FLOAT. PlacedFootprint::Offset is 16384, which requires the buffer to have 536657920 bytes; but the buffer only has 67108864 bytes. [ RESOURCE_MANIPULATION ERROR #869: COPYTEXTUREREGION_INVALIDSRCPLACEMENT]	
00000003	0.03093249	[9276] D3D12 WARNING: Process is terminating. Using simple reporting. Please call ReportLiveObjects() at runtime for standard reporting. [ STATE_CREATION WARNING #0: UNKNOWN]	
```

With a newer gfx version and the above mentioned shader patches, the issues in https://github.com/szeged/webrender/issues/53 seem to be solved.

NOTE: My working branch is not up to date with szeged/master at the moment, because we still have an issue(https://github.com/szeged/webrender/issues/68) on windows, which came in with https://github.com/szeged/webrender/pull/63.

**Comment by kvark** [comment]
> D2Array is not supported in gfx-rs yet:

Filed as https://github.com/gfx-rs/gfx/issues/1842

>  Change array return types in shaders to out parameters

Isn't this fixed in spirv-cross now? See https://github.com/KhronosGroup/SPIRV-Cross/pull/433

> Find out why the copy_buffer_to_image fails on the assert here

Please let us know if it's our issue!

**Comment by zakorgy** [comment]
We managed to pass trough the `copy_buffer_to_image` problem. We found two(3?) issues which caused the problems here:
- We provide wrong parameters to `copy_buffer_to_image` e.g. `buffer_width` should be the length of the image_data, but we use the length * data_stride. This will be fixed.
- Some of our buffer's width is smaller than the width of the image we want to write. This causes a panic [here](https://github.com/gfx-rs/gfx/blob/8d0ef5ba96bb4a2ecc5671975677323f11773dc5/src/backend/dx12/src/command.rs#L1289) 
- Some of the textures in webrender use width which is not multiple of 256. Namely Node texture has 1020 width and Rendertask texture has 1023 width. These are used to calculate row pitch, and it will be also not multiple of 256, causes [this assert](https://github.com/gfx-rs/gfx/blob/8d0ef5ba96bb4a2ecc5671975677323f11773dc5/src/backend/dx12/src/command.rs#L1294) fail.
- The last one is gfx related. When creating the D3D12_SUBRESOURCE_FOOTPRINT the [`height`](https://github.com/gfx-rs/gfx/blob/8d0ef5ba96bb4a2ecc5671975677323f11773dc5/src/backend/dx12/src/command.rs#L1305) variable should take the buffer offset in account. Because if the offset is not zero, the debug layer shows an error, that we want to write more bytes than the buffer size. A possible solution which worked for us, is to replace this [line](https://github.com/gfx-rs/gfx/blob/8d0ef5ba96bb4a2ecc5671975677323f11773dc5/src/backend/dx12/src/command.rs#L1296) with
```rust
let height = height as u32 - (region.buffer_offset as u32 / row_pitch);
```

**Comment by zakorgy** [comment]
> Isn't this fixed in spirv-cross now? See KhronosGroup/SPIRV-Cross#433

Looks like I missed the updates there. I will update my branch according to that.

**Comment by kvark** [comment]
Thanks, filed https://github.com/gfx-rs/gfx/issues/1843

**Comment by zakorgy** [comment]
We have managed to run WebRender with DX12. Instead of the boring `basic_hal` example image, here is a screen capture from the `border-suite` wrench test.
![dx12_borders](https://user-images.githubusercontent.com/11725775/37914178-e88dadb4-3116-11e8-8cd3-5d5d5188791f.PNG)

Here are the remaining issues:
- [ ] D2Array is still [not supported](https://github.com/gfx-rs/gfx/blob/master/src/backend/dx12/src/device.rs#L475) as RTV in gfx-rs, but D2 works fine.
- [ ] We worked around the subresource footprint [issue](https://github.com/gfx-rs/gfx/issues/1843) by updating the entire resource cache texture, not just the dirty parts of it.

cc @kvark

**Comment by kvark** [comment]
> D2Array is still not supported as RTV in gfx-rs, we use D2 instead of that.

oh snap, I missed that, sorry!
will cover ASAP

**Comment by kvark** [comment]
Addressed in https://github.com/gfx-rs/gfx/pull/1889
Note that the view creation API is to be changed soon in order to include the view type explicitly (e.g. allows viewing a cube image as 2D, etc)

**Comment by zakorgy** [comment]
Link for the branch: https://github.com/szeged/webrender/commits/dx12 .

**Comment by dati91** [comment]
We managed to track down some issues
- [ ] We need more than 256 when running the reftests
    - https://github.com/gfx-rs/gfx/blob/281e79864181973a530538b557e59de1db540122/src/backend/dx12/src/lib.rs#L497

- [ ] We only clear one layer, and the function check for all the layers
    - https://github.com/gfx-rs/gfx/blob/281e79864181973a530538b557e59de1db540122/src/backend/dx12/src/command.rs#L1029

- [ ] This seems wrong to me (also if you check it with the quad example without the aligment, it will fail)
  - https://github.com/gfx-rs/gfx/blob/281e79864181973a530538b557e59de1db540122/src/backend/dx12/src/command.rs#L746

- [ ] We use the calculated `row_pitch` with a different `width`
  - https://github.com/gfx-rs/gfx/blob/281e79864181973a530538b557e59de1db540122/src/backend/dx12/src/command.rs#L751

- [ ] As before, we use a `row_pitch` with a different `width`
  - https://github.com/gfx-rs/gfx/blob/281e79864181973a530538b557e59de1db540122/src/backend/dx12/src/command.rs#L783)

- An example error for the `row_pitch`
  - `[21996] D3D12 ERROR: ID3D12CommandList::CopyTextureRegion: D3D12_SUBRESOURCE_FOOTPRINT::RowPitch must be a multiple of 256 (aka. D3D12_TEXTURE_DATA_PITCH_ALIGNMENT) and greater or equal to the pitch implied by the width. RowPitch is 768, and must be greater or equal to 880 when D3D12_SUBRESOURCE_FOOTPRINT::Width is 220 and D3D12_SUBRESOURCE_FOOTPRINT::Format is B8G8R8A8_UNORM. [ RESOURCE_MANIPULATION ERROR #868: COPYTEXTUREREGION_INVALIDSRCROWPITCH]`
  - Even if it calculates the right `row_pitch` for the first call, it fails on the second call

**Comment by kvark** [comment]
Great findings! Please file those issues upstream in gfx-rs for us to see and address.

**Comment by kvark** [comment]
I'll address the buffer-image copy issues ASAP. Filed https://github.com/gfx-rs/gfx/issues/1943 for the clear. Leaving the first one to you :)

**Comment by kvark** [comment]
The first two problems are now resolved by https://github.com/gfx-rs/gfx/pull/1954

**Comment by dati91** [comment]
The only remaining thing is blitting, and we track it [here](https://github.com/szeged/webrender/issues/134), so i'm closing this.
