### ISSUE TITLE
Create Image View type mismach

### ISSUE THREAD

**Issue by dati91** [szeged/webrender#84]
```
### Image::new before D2Array(2048, 2048, 4, Single)
### ImageCore create D2Array(2048, 2048, 4, Single) SubresourceRange { aspects: COLOR, levels: 0..1, layers: 0..4 }
### from_image Bgra8Unorm SubresourceRange { aspects: COLOR, levels: 0..1, layers: 0..4 }
ERROR:<unknown>: [ParameterValidation] vkCreateImageView: if pCreateInfo->viewType is VK_IMAGE_TYPE_2D, pCreateInfo->subresourceRange.layerCount must be 1
### from_image after
### Image::new after
```

We try to create an image view with 4 layer for a 2D_ARRAY image, but the result is a 2D image view.

After digging into this i found that [this](https://github.com/gfx-rs/gfx/blob/master/src/backend/vulkan/src/device.rs#L1018) should be [`vk::ImageViewType::Type2dArray`](https://github.com/MaikKlein/ash/blob/master/ash/src/vk.rs#L3067).
(See https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#resources-image-views-compatibility)

My guess is that this will also fix this error:
```
ERROR:: [DS] Descriptor set 0x4e encountered the following validation error at vkCmdDraw() time: Descriptor in binding #1 at global descriptor index 1 requires an image view of type VK_IMAGE_VIEW_TYPE_2D_ARRAY but got VK_IMAGE_VIEW_TYPE_2D.
```

cc @kvark

**Comment by kvark** [comment]
Is this an upstream (gfx-hal) issue? we aren't selecting the view type properly?

**Comment by dati91** [comment]
Yes, I used (and linked) the master and there is a big `TODO` [here](https://github.com/gfx-rs/gfx/blob/master/src/backend/vulkan/src/device.rs#L1018).

**Comment by dati91** [comment]
Filled an issue: https://github.com/gfx-rs/gfx/issues/1874

**Comment by zakorgy** [comment]
Updating gfx-rs solved this issue too.
