### ISSUE TITLE
Use buffer alignment

### ISSUE THREAD

**Issue by zakorgy** [szeged/webrender#89]
We don't use the `min_buffer_copy_pitch_alignment` provided by the physical device when creating our Buffer-s. This can be related to #68 and https://github.com/szeged/webrender/issues/73#issuecomment-367376219.

**Comment by dati91** [comment]
I reverted the previous PR because there was some regression. https://github.com/szeged/webrender/commit/a86d7a6e00137a7ad1a891c1b3909536fea73411

**Comment by zakorgy** [comment]
There are still some corner cases, which needs correction.
If the target destination image's width is not aligned according to the copy_buffer_alignment, and we write (copy_buffer_to_image) it from an aligned buffer, the texture on the image is shifted with an offset in each line.

**Comment by kvark** [comment]
This is to be handled automatically by https://github.com/gfx-rs/gfx/pull/1893, at least on DX12.
We will likely remove the minimum aligned requirement completely, matching Vulkan here.

**Comment by dati91** [comment]
Closed via #130
